<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E0452666" ignored="0" name="Run All Tests" tests="5" failures="1" timestamp="2020-03-25T16:22:28 EET" time="93.495" errors="0">
  <testcase name="runScenario" time="14.268" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="9.427" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Thank you for your message!] but found [Dear Customer,]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Thank you for your message!] but found [Dear Customer,]
at SampleTestCucumber.StepDefs.FunctionalTestStepDefs.he_should_be_navigated_to_success_page_with_message(FunctionalTestStepDefs.java:76)
at âœ½.he should be navigated to success page with message "Thank you for your message!"(src/test/java/Features/FunctionalTest.feature:12)
... Removed 1 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="3.033" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="1.92" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="0.927" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Run All Tests -->
