<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="E0452666" name="SampleTestCucumber.TestRunner" tests="5" failures="1" timestamp="2020-03-25T16:22:28 EET" time="29.575" errors="0">
  <testcase name="runScenario" time="9.427" classname="SampleTestCucumber.TestRunner">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Thank you for your message!] but found [Dear Customer,]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Thank you for your message!] but found [Dear Customer,]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:42)
at SampleTestCucumber.StepDefs.FunctionalTestStepDefs.he_should_be_navigated_to_success_page_with_message(FunctionalTestStepDefs.java:76)
at âœ½.he should be navigated to success page with message "Thank you for your message!"(src/test/java/Features/FunctionalTest.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.927" classname="SampleTestCucumber.TestRunner"/>
  <testcase name="runScenario" time="1.920" classname="SampleTestCucumber.TestRunner"/>
  <testcase name="runScenario" time="3.033" classname="SampleTestCucumber.TestRunner"/>
  <testcase name="runScenario" time="14.268" classname="SampleTestCucumber.TestRunner"/>
</testsuite> <!-- SampleTestCucumber.TestRunner -->
